name: Release to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: Call Centralized PyPI Release
    permissions:
      contents: write
    uses: Economistician/eb-integration/.github/workflows/pypi-release.yml@main
    with:
      python-version: "3.13"
      build-command: "python -m build --sdist --wheel"
    secrets: inherit
